[project]
name = "magtrack"
version = "1.0.0"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }


[project.scripts]
traintrack-dataset = "magtrack.cli.traintrack_dataset:app"
evaluate-nor-tmd = "magtrack.cli.evaluate_nor_tmd:app"
create-tmd-dataset = "magtrack.cli.create_tmd_dataset:app"
evaluate-tmd = "magtrack.cli.evaluate_tmd:app"
create-colocation-dataset = "magtrack.cli.create_colocation_dataset:app"
evaluate-coloc-distance = "magtrack.cli.evaluate_coloc_distance:app"
hyperparameter-search = "magtrack.cli.hyperparameter_search:app"
train-ml-model = "magtrack.cli.train_ml_model:app"
ml-inference = "magtrack.cli.ml_inference:main"
evaluate-majority-ml = "magtrack.cli.evaluate_majority_ml:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
