input_channels: 2
embedding_dim: 64
num_conv_layers: 4
base_channels: 64
kernel_size: 3
stride: 1
pool_kernel: 3
fc_hidden_dims:
- 512
- 256
fc_dropout: 0.17125548897250764
hz: 10
window_size_seconds: 10
chunk_size_seconds: 60
train_ride_start_seconds: 300
lr: 0.03
batch_size: 256
weight_decay: 9.517131427515421e-05
